---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/mvnfinal/target/mvnfinal.war"
        dest: "/opt/tomcat/webapps/mvnfinal.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:   
        name: tomcat
        state: restarted
